version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - my_network

  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: my_mariadb_container
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:

volumes:
  mariadb_data: