version: '3.8'

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - my_network

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: my_mariadb_container
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:

volumes:
  mariadb_data: