version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    container_name: my-nginx
    volumes:
      - ./nginx/nginx-html:/usr/share/nginx/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress

  wordpress:
    build:
      context: ./wordpress
    container_name: my-wordpress
    volumes:
      - ./data/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./mariadb
    container_name: my-mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password

volumes:
  mariadb_data:
networks:
  default:
    driver: bridge